"""Add Hybrid Freeze finalization columns

Revision ID: 5d971737cc6a
Revises: ced6f7807fd8
Create Date: 2026-03-09 03:26:21.542675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d971737cc6a'
down_revision: Union[str, Sequence[str], None] = 'ced6f7807fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop temporary_extraction (created in initial migration, no longer needed)
    op.execute("DROP INDEX IF EXISTS ix_temporary_extraction_id")
    op.execute("DROP INDEX IF EXISTS ix_temporary_extraction_user_id")
    op.execute("DROP TABLE IF EXISTS temporary_extraction")

    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("(now() + '00:30:00'::interval)"))

    # Add finalization hybrid columns to user_initial
    op.add_column('user_initial', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user_initial', sa.Column('father_name', sa.String(), nullable=True))
    op.add_column('user_initial', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user_initial', sa.Column('dob', sa.String(), nullable=True))
    op.add_column('user_initial', sa.Column('aadhar_id', sa.String(), nullable=True))
    op.add_column('user_initial', sa.Column('pan_id', sa.String(), nullable=True))
    op.add_column('user_initial', sa.Column('raw_archive', sa.JSON(), nullable=True))




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_initial', 'raw_archive')
    op.drop_column('user_initial', 'pan_id')
    op.drop_column('user_initial', 'aadhar_id')
    op.drop_column('user_initial', 'dob')
    op.drop_column('user_initial', 'address')
    op.drop_column('user_initial', 'father_name')
    op.drop_column('user_initial', 'name')
    op.drop_index(op.f('ix_user_documents_session_id'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_document_id'), table_name='user_documents')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text("(now() + '00:30:00'::interval)"))
    op.create_table('temporary_extraction',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extracted_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_initial.id'], name=op.f('temporary_extraction_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('temporary_extraction_pkey'))
    )
    op.create_index(op.f('ix_temporary_extraction_user_id'), 'temporary_extraction', ['user_id'], unique=False)
    op.create_index(op.f('ix_temporary_extraction_id'), 'temporary_extraction', ['id'], unique=False)
    # ### end Alembic commands ###
